version: '3.7'

services:

  php:
    build: docker/images/php-fpm
    image: ${APP_NAME}-php:develop
    container_name: ${APP_NAME}-php
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/app

  web:
    build: docker/images/nginx
    image: ${APP_NAME}-web:develop
    container_name: ${APP_NAME}-web
    restart: always
    volumes:
      - .:/var/www/app
    ports:
      - '${WEB_PORT}:80'
    depends_on:
      - php

  db:
    image: postgres:11.6
    container_name: ${APP_NAME}-db
    restart: always
    volumes:
      - ./data:/var/data
    environment:
      POSTGRES_USER: ${DATABASE_ADMIN}
      POSTGRES_PASSWORD: ${DATABASE_ADMIN_PASSWORD}

  adminer:
    image: adminer
    container_name: ${APP_NAME}-adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080
